### ISSUE TITLE
GraphQL API should be camelCase

### ISSUE THREAD

**Issue by benji6** [robcalcroft/reflect#21]
Right now it is snake_case because data is returned unformatted from the DB. We should do the formatting in the model layer so the rest of the application can work with camelCase

**Comment by robcalcroft** [comment]
We could also do this in the query itself with `select camel_case as camelCase from table` but this could be the wrong layer to add this logic

**Comment by benji6** [comment]
ah yeah that's true, I actually don't know, maybe that would be nicer 🤔

**Comment by robcalcroft** [comment]
Closed in #23

**Comment by benji6** [comment]
#23 only fixed the board queries, still need to go through the other ones too

**Comment by robcalcroft** [comment]
Ah! Whoops
