### ISSUE TITLE
Build UI for creating lists

### ISSUE THREAD

**Issue by robcalcroft** [robcalcroft/reflect#29]

**Comment by benji6** [comment]
Do you reckon creating lists should be part of board creation? I'm just imagining that the user probably doesn't want to alter the lists once the board has been created (and I'm pretty sure they couldn't as soon as there are cards in those lists).

I'm wondering if they just have a quick form that asks them for a board name and some list names and then the board is created and that's that. Down the line we could add templates so the user doesn't have to write out the list names every time

**Comment by robcalcroft** [comment]
Yeah that sounds good to me!

**Comment by robcalcroft** [comment]
Closed in #36 

When we do the boards UI we can copy some of the logic from this to create a default set of lists
